info: '128x128, fg/bg (new discrim), lpips_alex percep'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.fgbg.FgBgFacegenDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.aae_fgbg.FgBgAaeTrainer'
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.ae.fgbg.FgBgAutoencoder'
        e_pri_layers_per_res: [2, 4, 8, 4, 2]
    D:
        type: 'ai_old.nn.models.discriminate.fgbg.FgBgDiscriminator'
        combo_imsize: 64

loss:
    type: 'ai_old.loss.aae_fgbg.FgBgAaeLoss'
    G:
        rec:
            weight: 10
            perceptual_type: 'lpips_alex'
    D:
        gp:
            freq: 16
            weight: 'auto'
