info: '256x256, full bottleneck aae, ahanu v0 percep, heavier rec weight'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.Ffhq256GanDataset'
    imsize: 256
    # batch_size: 'auto'
    batch_size: 8
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.aae.AaeTrainer'
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.ae.full.FullBottleneckAutoencoder'
        g_type: 'zosd'
        e_pri_fmtl_type: 'learned_hybrid'
        e_pri_layers_per_res: [2, 2, 4, 8, 4, 2]
    D:
        type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.aae.SimpleAaeLoss'
    G:
        rec:
            weight: 20
            perceptual_type: 'ahanu'
            perceptual_version: 0
    D:
        gp:
            freq: 16
            weight: 'auto'
