info: '256x256, additional 8x8/64x64 blocks'
task: 'ai_old.task.tmp.TmpFacegenTask'
seed: 0
fp32: False
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.fgbg.FgBg256FacegenDataset'
    imsize: 256
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.fgbg.FgBgStyleGanTrainer'
    style_mix_prob: 0.9
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    init_from_exp: null
    G:
        type: 'ai_old.nn.models.facegen.fgbg.FgBgGenerator'
        additional_resolutions: [8, 64]
    D:
        type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        nc_in: 4
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.fgbg.FgBgStyleGanLoss'
    G:
        ppl:
            freq: 4
            weight: 2
            decay: 0.01
            batch_shrink: 2
    D:
        gp:
            freq: 16
            weight: 'auto'
