info: 'style g and ae d'
task: 'ai_old.task.facegen.facegen.FacegenTask'

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    batch_size: 16

trainer:
    type: 'ai_old.trainer.gan.ModelCustomizedGanTrainer'
    n_epochs: 800
    model_ema: True

opt:
    type: 'adabelief'
    hparams: 'small_gan'
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.facegen.style.StyleGeneratorWrapper'

loss:
    type: 'ai_old.loss.ppl.PplRegGLoss'
    gan:
        type: 'hinge'
        weight: 1
    ppl:
        freq: 32
        weight: 1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.CutmixRegDiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.ae.AutoencoderDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.AutoencoderRegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        rec:
            weight: 1
        gp:
            freq: 4
            weight: 10

    opt:
        type: 'adabelief'
        hparams: 'small_gan'
        sch: 'flat_cosine'
