info: 'ae, 128x128, simple w e, low res style g'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 32
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.rec.RecTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.ae.style.StyleAutoencoder'
    e_type: 'simple_w'
    e_nc_base: 64
    e_norm_first_block: False
    g_type: 'low_res_style'
    g_nc_base: 8
    g_noise_mode: 'const'

loss:
    type: 'ai_old.loss.rec.CustomRecLoss'
    face:
        weight: 0.1
    perceptual:
        type: 'lpips_alex'
        weight: 0.8
