name: 'build paired dataset from old paired dataset'
inferencer: 'ai_old.inf.pairedgender.PairedGenderDatasetBuilder'

deps:
    facegen:
        path: 'stylegan/stylegan2-ffhq-config-f.pt'
        frozen: True
        strict: False
    gender:
        exp: 'gender/0/base'
        type: 'ai_old.models.c.transfer.TransferMlpClassifier'
        key: 'c'
        frozen: True
    mtf:
        lerp: 'mtf/0.gz'
    seg:
        path: 'deeplab/deeplab_model.pth'
        frozen: True
    facerecog_loss:
        path: 'arcface/model_ir_se50.pth'
        frozen: True
        strict: False

dataset:
    type: 'rgb2rgb'
    name: 'mtf-gen-256'
    imsize: 256

model:
    g:
        type: 'dep'
        dep: 'facegen'
    c:
        type: 'dep'
        dep: 'gender'
    t:
        type: 'dep'
        dep: 'mtf'
    seg:
        type: 'dep'
        dep: 'seg'

inf:
    batch_size: 1
    truncation: 0.7
