info: 'light e, light pretrained g, lpips guide'
task: 'ai_old.task.rec.rec.RecTask'

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    batch_size: 32

trainer:
    type: 'ai_old.trainer.gan.RecGanTrainer'
    n_epochs: 800
    model_ema: True

opt:
    type: 'adabelief'
    hparams: 'small_gan'
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.encgen.simple.SimpleRecOnlyEncGen'
    g_init_from_exp: 'facegen/4/1'
    g_unfreeze_at_epoch: 40

loss:
    type: 'ai_old.loss.iit.gan.GuidedGLoss'
    gan:
        type: 'hinge'
        weight: 1
    lpips:
        weight: 1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.DiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.ae.AutoencoderDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.AutoencoderRegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        rec:
            weight: 1
        gp:
            freq: 4
            weight: 10

    opt:
        type: 'adabelief'
        hparams: 'small_gan'
        sch: 'flat_cosine'
