info: 'aae'
task: 'ai_old.task.tmp.TmpRecTask'
seed: 0
fp32: False
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.aae.AaeTrainer'
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.encgen.ae.ModspaceAutoencoder'
        zspace_ae_exp: 'rec/12/2'
        reset_e_pri: true
        freeze_e_pri: false
        freeze_g: false
        e_mod_type: 'style'
    D:
        exp: 'facegen/8/1'

loss:
    type: 'ai_old.loss.aae.SimpleAaeLoss'
    G:
        rec:
            weight: 1
    D:
        gp:
            freq: 16
            weight: 'auto'
