info: 'full bottleneck ae swap'
task: 'ai_old.task.swap.SwapTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 100000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.ult.UltDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.swap.SynthOnlySwapTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.swap.simple.SimpleSwapper'
    ae_exp: 'rec/21/3'
    z_dims: 512
    version: 'v0'

loss:
    type: 'ai_old.loss.swap.SynthOnlySwapLoss'
