info: 'aot inpainter 512x512'
task: 'ai_old.task.outpaint.OutpaintTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.outpaint.Outpaint512Dataset'
    imsize: 512
    inner_imsize: 341
    batch_size: 4
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.outpaint.SmartOutpaintAaeTrainer'
    mask_provided: true
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'color'

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.inpaint.aot.AotInpainter'
    D:
        type: 'ai_old.nn.models.discriminate.inpaint.InpaintDiscriminator'
        include_mask: false
        nc_base: 32
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.aae.SmartOutpaintLoss'
    G:
        rec:
            enabled: true
            perceptual_type: 'lpips_alex'
            weight: 10.
    D:
        gp:
            freq: 16
            weight: 'auto'
