info: 'real only w_plus swap'
task: 'ai_old.task.w_plus.SwapTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 40000

dataset:
    type: 'ai_old.dataset.w_plus.RealOnlySwapDataset'
    imsize: 1024
    batch_size: 'auto'
    # batch_size: 8
    batch_gpu: 'auto'
    xflip: False

trainer:
    type: 'ai_old.trainer.w_plus.RealOnlySwapTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.swap.w_plus.SwapperAndGenerator'

loss:
    type: 'ai_old.loss.w_plus.RealOnlyClipIdSwapLoss'
    clip:
        female_male_target_texts: ['male face', 'female face']
        weight: 1.
        dir: false
    id:
        weight: 0.1
    delta:
        weight: 0.8
        ord: 2
