info: 'res g and unet d with gp reg and lpips guide'
task: 'ai_old.task.genderswap.static.StaticMtfTask'

dataset:
    type: 'ai_old.dataset.synthswap.pg.PairedGenderDataset'
    batch_size: 16

trainer:
    type: 'ai_old.trainer.gan.ConditionalGanTrainer'
    n_epochs: 100

opt:
    type: 'adabelief'
    hparams: 'small_gan'
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.iit.res.ResIIT'

loss:
    type: 'ai_old.loss.unet.UnetGLoss'
    enc:
        weight: 1
    dec:
        weight: [0, 1, 30000]
    lpips:
        weight: 1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.PairedImgDiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.unet.UnetDiscriminator'
        nc_in: 6

    loss:
        type: 'ai_old.loss.unet.UnetDLoss'
        enc:
            weight: 1
        dec:
            weight: [0, 1, 30000]
        gp_enc:
            freq: 4
            weight: 10
        gp_dec:
            freq: 4
            weight: [0, 10, 30000]

    opt:
        type: 'adabelief'
        hparams: 'small_gan'
        sch: 'flat_cosine'
