info: 'static male-to-female gender swap using res g and autoencoder d'
task: 'ai_old.task.genderswap.static.StaticMtfTask'

dataset:
    type: 'ai_old.dataset.synthswap.pg.PairedGenderDataset'
    batch_size: 32
    split: 0.99

trainer:
    type: 'ai_old.trainer.gan.ConditionalGanTrainer'
    n_epochs: 40

opt:
    type: 'ranger'
    lr: 0.001
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.iit.res.ResIIT'

loss:
    type: 'ai_old.loss.iit.gan.GuidedGLoss'
    gan:
        type: 'hinge'
        weight: 1
    lpips:
        weight: 1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.DiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.ae.AutoencoderDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.AutoencoderRegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        rec:
            weight: 1

    opt:
        type: 'ranger'
        lr: 0.001
        sch: 'flat_cosine'
