info: 'unet g and unet d with gp and cutmix reg and lpips guide'
task: 'ai_old.task.genderswap.static.StaticMtfTask'

dataset:
    type: 'ai_old.dataset.synthswap.pg.PairedGenderDataset'
    batch_size: 16

trainer:
    type: 'ai_old.trainer.gan.ConditionalGanTrainer'
    n_epochs: 200

opt:
    type: 'adabelief'
    hparams: 'small_gan'
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.iit.unet.UnetIIT'

loss:
    type: 'ai_old.loss.unet.UnetGLoss'
    enc:
        weight: 1
    dec:
        weight: [0, 1, 30000]
    lpips:
        weight: 1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.PairedImgCutmixRegDiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.unet.UnetDiscriminator'
        nc_in: 6

    loss:
        type: 'ai_old.loss.unet.UnetDLoss'
        enc:
            weight: 1
        dec:
            weight: [0, 1, 30000]
        gp_enc:
            freq: 4
            weight: 10
        gp_dec:
            freq: [4, 2]
            weight: [0, 10, 30000]
        cutmix:
            prob: [0, 0.25, 30000]
            weight: [0, 1, 30000]
            fake_label: 'fake_concat'
            real_label: 'real_concat'

    opt:
        type: 'adabelief'
        hparams: 'small_gan'
        sch: 'flat_cosine'
