info: 'seg from gen'
task: 'ai_old.task.seg.SegFromGenTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 4000

dataset:
    type: 'ai_old.dataset.seg.SegFromGenDataset'
    imsize: 128
    # batch_size: 'auto'
    batch_size: 8
    batch_gpu: 'auto'
    xflip: False

trainer:
    type: 'ai_old.trainer.seg.SegFromGenTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.seg.style.SegmenterAndGenerator'

loss:
    type: 'ai_old.loss.seg.SegLoss'
