name: 'hair stylegan latent'
trainer: 'ai_old.trainers.attrlatent.HairAttrLatent'

dataset:
    type: 'dualgaussian'
    dims1: 512
    dims2: 8
    n_train: 1000
    n_val: 10
    n_inf: 10

model:
    g:
        type: 'ai_old.models.g.stylegan.Generator'
        path: 'stylegan/stylegan2-ffhq-config-f.pt'
    t:
        type: 'ai_old.models.t.mlp.SgMlpTransformer'
        dims1: 8
        hidden: [16, 32, 64, 128, 256]
        dims2: 512
        lr_mul: 1
    seg:
        type: 'ai_old.models.seg.deeplab.FaceSegmenter'
        n_classes: 19
        path: 'deeplab/deeplab_model.pth'

train:
    epochs: 20
    batch_size: 1
    g_truncation: 0.7
    transform_only_steps: 10 # decays by 1 every epoch
    loss:
        mag:
            ymult: 0.1 # larger means delta-z is smaller on avg
        nonhair:
            weight: 10.
        hairtexture:
            weight: 1.
        hairshape:
            weight: 10.
    opt:
        lr: 0.002
        step_size: 10
        gamma: 0.1

inf:
    batch_size: 1
    g_truncation: 0.5
