name: 'fluid gender classifier'
trainer: 'ai_old.trainers.regression.MSETrainer'
inferencer: 'ai_old.inf.regression.ImgRegression'

dataset:
    type: 'continuousgender'
    name: 'delta-g-64'
    split: 0.997
    size: 64
    aug:
        flip: True

model:
    c:
        type: 'ai_old.models.c.gender.FluidGenderClassifier'
        nc_in: 3
        nc: 64
        n_down: 1
        n_res: 4
        padding: 'reflect'
        weight_norm: True
        activation: 'lrelu'
        norm: 'batch'

train:
    epochs: 5
    batch_size: 32
    opt:
        lr: 0.01
        step_size: 2
        gamma: 0.5

inf:
    batch_size: 32
