name: 'mk2 mini'
trainer: 'ai_old.trainers.mk2experimental.Mk2Trainer'

dataset:
    type: 'mk2'
    size: 64
    paired: 'delta-g-64'
    unpaired: 'itw'
    split: 0.99
    exp: 19 # continuous gender classifier
    aug:
        flip: True

model:
    gender_dims: 128
    disentangled_dims: 128
    size: 1 # n down in e, n up in g
    nc: 16 # base nc used in several submodels
    iit:
        type: 'ai_old.models.combined.mk2.Mk2iit'
    e:
        type: 'ai_old.models.e.identity.IdentityEncoder'
        nc_in: 3
        n_res: 2
        norm: 'pixel'
        padding: 'reflect'
        weight_norm: True
        activation: 'relu'
    g:
        type: 'ai_old.models.g.style.StyleGenerator'
        norm: 'pixel'
        padding: 'reflect'
        weight_norm: True
        activation: 'lrelu'
    t:
        type: 'ai_old.models.t.mlp.GenderMlpTransformer'
        hidden: [128, 128, 128, 128]
        norm: 'pixel'
        weight_norm: True
        activation: 'lrelu'

train:
    avg: False
    loss:
        paired:
            weight: 1.
        mag:
            weight: 100.
            delta_g_mult: 1.
    epochs: 40
    batch_size: 32
    iit:
        lr: 0.001
        beta1: 0.
        beta2: 0.999
        gamma: 0.5
        step_size: 10
