name: 'fluid gender classifier'
trainer: 'ai_old.trainers.regression.MSETrainer'
inferencer: 'ai_old.inf.regression.ImgRegression'

dataset:
    type: 'continuousgender'
    name: 'delta-g-256'
    split: 0.999
    size: 256
    aug:
        flip: True

model:
    c:
        type: 'ai_old.models.c.gender.FluidGenderClassifier'
        nc_in: 3
        nc: 32
        n_down: 3
        n_res: 4
        padding: 'reflect'
        weight_norm: True
        activation: 'lrelu'
        norm: 'batch'

train:
    epochs: 20
    batch_size: 32
    opt:
        lr: 0.005
        step_size: 9
        gamma: 0.5

inf:
    batch_size: 32
