name: 'mk2 mini live inf'
inferencer: 'ai_old.inf.mk2.Mk2'
debug: True

dataset:
    type: 'rgb'
    size: 64

model:
    gender_dims: 128
    disentangled_dims: 128
    size: 1 # n down in e, n up in g
    nc: 16 # base nc used in several submodels
    iit:
        type: 'ai_old.models.combined.mk2.Mk2iit'
        exp: 18
    e:
        type: 'ai_old.models.e.identity.IdentityEncoder'
        nc_in: 3
        n_res: 2
        norm: 'pixel'
        padding: 'reflect'
        weight_norm: True
        activation: 'relu'
    c:
        type: 'ai_old.models.c.gender.FluidGenderClassifier'
        exp: 19
        nc_in: 3
        nc: 64
        n_res: 4
        n_down: 1
        padding: 'reflect'
        weight_norm: True
        activation: 'lrelu'
        norm: 'batch'
    g:
        type: 'ai_old.models.g.style.StyleGenerator'
        norm: 'pixel'
        padding: 'reflect'
        weight_norm: True
        activation: 'lrelu'
    t:
        type: 'ai_old.models.t.mlp.GenderMlpTransformer'
        hidden: [128, 128, 128, 128]
        norm: 'pixel'
        weight_norm: True
        activation: 'lrelu'
    d:
        type: 'ai_old.models.d.style.StyleDiscriminator'
        cdiv: 16

inf:
    batch_size: 1
