info: '[fg] no swap rec, pixel only, excite g, small unet adversary'
task: 'ai_old.task.ult.UltTask'

dataset:
    type: 'ai_old.dataset.ult.FgUltDataset'
    batch_size: 32

trainer:
    type: 'ai_old.trainer.ult.UltTrainer'
    n_epochs: 800
    model_ema: False

opt:
    type: 'adam'
    lr: 0.0002
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.encgen.ult.UltModel'
    real_enabled: true
    gan_enabled: true
    swap_enabled: true
    swap_rec_enabled: false
    z_dims: 256
    nc_base: 16
    nc_max: 256
    f_n_layers: 4
    g: 'excitation'

loss:
    type: 'ai_old.loss.ult.UltLoss'
    # real_rec_perceptual:
    #     weight: 10
    # real_rec_face:
    #     weight: 1
    real_rec_pixel:
        # weight: 10
        weight: 20
    gender:
        weight: 1
    gan_enc:
        weight: 1
    gan_dec:
        weight: [0, 1, 10000]
    dz_mtf:
        weight: 1
    dz_ftm:
        weight: 1
    identity:
        weight: 0.1

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.UltCutmixDiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.unet.UnetDiscriminator'
        nc_base: 16
        nc_max: 256
        n_res: 1

    loss:
        type: 'ai_old.loss.unet.UnetDLoss'
        real_label: 'real'
        enc:
            weight: 1
        dec:
            weight: [0, 1, 10000]
        gp_enc:
            freq: 4
            weight: 10
        gp_dec:
            freq: [4, 2]
            weight: [0, 10, 10000]
        cutmix:
            prob: [0, 0.25, 10000]
            weight: [0, 1, 10000]

    opt:
        type: 'adam'
        lr: 0.0008
        sch: 'flat_cosine'
