info: 'rec, init with invert/0/0'
task: 'ai_old.task.tmp.TmpRecTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 16
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.rec.RecTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.encgen.ae.GeneratorInitializedAutoencoder'
    exp: 'invert/0/0'

loss:
    type: 'ai_old.loss.rec.SimpleRecLoss'
