info: 'distill 128x128 (not convertible), nc base 8'
task: 'ai_old.task.distill.Sg2DistillTask'
seed: 0
fp32: false
n_steps: 25000000

dataset:
    type: 'ai_old.dataset.w_plus.InvSwap128Dataset'
    imsize: 128
    batch_size: 32
    batch_gpu: 'auto'
    xflip: false

trainer:
    type: 'ai_old.trainer.distill.Sg2DistillTrainer'
    freeze_first_half: false
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.facegen.low_res.LowResGenerator'
        nc_base: 8
    D:
        type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.distill.Sg2DistillLoss'
    G:
        rec:
            weight: 10
            perceptual_type: 'lpips_alex'
    D:
        gp:
            freq: 16
            weight: 'auto'
