info: 'e4e, 0 delta'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    # batch_size: 8
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.e4e.E4eTrainer'
    cliff: 20000
    # cliff: 1
    inc: 2000
    # inc: 1

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.encgen.e4e.E4e'
    imsize: 128
    e_type: 'e4e'
    g_exp: 'facegen/8/3'

loss:
    type: 'ai_old.loss.rec.E4eFancyRecLoss'
    perceptual_type: 'lpips'
    delta_weight: 0.
