info: 'restyle psp'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    # batch_size: 'auto'
    batch_size: 4
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.restyle.RestylePspTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.encgen.psp.RestylePsp'
    imsize: 128
    e_type: 'psp'
    g_exp: 'facegen/8/3'

loss:
    type: 'ai_old.loss.rec.RestyleFancyRecLoss'
    perceptual_type: 'lpips'
