info: 'blend modspace swap'
task: 'ai_old.task.swap.SwapTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 100000

dataset:
    type: 'ai_old.dataset.swap.BlendSwapDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.swap.BlendSwapTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.transform.swap.BlendModspaceSwap'
    rec_exp: 'blend-rec/1/0'
    n_mlp_layers: 2

loss:
    type: 'ai_old.loss.swap.BlendSwapLoss'
