info: 'modspace swap'
task: 'ai_old.task.swap.SwapTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 100000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.swap.SwapDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.swap.SwapTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.transform.swap.ModspaceSwap'
    rec_exp: 'rec/14/1'
    n_mlp_layers: 2

loss:
    type: 'ai_old.loss.swap.SwapLoss'
