info: 'debug'
task: 'ai_old.task.genderswap.static.StaticMtfTask'

dataset:
    type: 'ai_old.dataset.synthswap.pg.PairedGenderDataset'
    batch_size: 16

trainer:
    type: 'ai_old.trainer.gan.ConditionalGanTrainer'
    n_epochs: 100

opt:
    type: 'adabelief'
    hparams: 'small_gan'
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.iit.res.ResIIT'

loss:
    type: 'ai_old.loss.gan.GLoss'
    gan:
        type: 'softplus'

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.PairedImgDiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.style.StyleDiscriminator'
        nc_in: 6 # dual rgb
        channels: [512, 512, 512, 256, 128, 64]

    loss:
        type: 'ai_old.loss.gan.DLoss'
        gan:
            type: 'softplus'

    opt:
        type: 'adabelief'
        hparams: 'small_gan'
        sch: 'flat_cosine'
