info: 'facegen/8/1 with ibg blending'
task: 'ai_old.task.blend.BlendFacegenTask'
seed: 0
fp32: False
n_steps: 25000000

dataset:
    type: 'ai_old.dataset.realface.ffhq.BlendFfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.cgan.BlendStyleGanTrainer'
    style_mix_prob: 0.9
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    init_from_exp: null
    G:
        type: 'ai_old.nn.models.facegen.blend.BlendGenerator'
        imsize: 128
        z_dims: 512
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4
        f_n_layers: 2
    D:
        type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        imsize: 128
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.stylegan.BlendStyleGanLoss'
    G:
        ppl:
            freq: 4
            weight: 2
            decay: 0.01
            batch_shrink: 2
    D:
        gp:
            freq: 16
            weight: 'auto'
