info: 'ult excitation g and ae d, extra small'
task: 'ai_old.task.facegen.facegen.FacegenTask'

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    batch_size: 32

trainer:
    type: 'ai_old.trainer.gan.GanTrainer'
    n_epochs: 800
    model_ema: False

opt:
    type: 'adam'
    lr: 0.0002
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.facegen.ult.GenOnlyUltModel'
    z_dims: 256
    nc_base: 16
    nc_max: 256
    f_n_layers: 4

loss:
    type: 'ai_old.loss.gan.GLoss'
    gan:
        type: 'hinge'

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.DiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.ae.AutoencoderDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.AutoencoderRegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        rec:
            weight: 1
        gp:
            freq: 4
            weight: 10

    opt:
        type: 'adam'
        lr: 0.0008
        sch: 'flat_cosine'
