info: 'ult excitation g and style d'
task: 'ai_old.task.facegen.facegen.FacegenTask'

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    batch_size: 32

trainer:
    type: 'ai_old.trainer.gan.GanTrainer'
    n_epochs: 800
    model_ema: False

opt:
    type: 'adam'
    lr: 0.0001
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.facegen.ult.GenOnlyUltModel'
    z_dims: 512
    nc_base: 32
    nc_max: 512
    f_n_layers: 4

loss:
    type: 'ai_old.loss.gan.GLoss'
    gan:
        type: 'hinge'

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.DiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.style.StyleDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.RegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        gp:
            freq: 4
            weight: 10

    opt:
        type: 'adam'
        lr: 0.0004
        sch: 'flat_cosine'
