#!/usr/bin/env python3
from ai_old.devserver.auth.authenticator import Authenticator
import getpass

email = input('Email?: ')
password0 = getpass.getpass('New password?: ')
password1 = getpass.getpass('Again?: ')

if password0 != password1:
    print('Passwords don\'t match.')
else:
    auth_manager = Authenticator(None)
    auth_manager.change_password(email, password0)
