#!/usr/bin/env python3
from PIL import Image
from torchvision.transforms import ColorJitter
import numpy as np

im = Image.open('/home/calvin/datasets/mtf-gen-256/test_A/1247400.png').convert('RGB')

# for x in np.arange(0.5, 1.51, 0.125):
#     ColorJitter(brightness=(x, x))(im).save(
#         '/home/calvin/storage/tmp/b{}.png'.format(x), 'PNG')
#     ColorJitter(contrast=(x, x))(im).save(
#         '/home/calvin/storage/tmp/c{}.png'.format(x), 'PNG')
#     ColorJitter(saturation=(x, x))(im).save(
#         '/home/calvin/storage/tmp/s{}.png'.format(x), 'PNG')
#     ColorJitter(hue=((x-1.)/10., (x-1.)/10.))(im).save(
#         '/home/calvin/storage/tmp/h{}.png'.format(x), 'PNG')

for i in range(100):
    ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3)(im).save(
        '/home/calvin/storage/tmp/b{}.png'.format(i), 'PNG')
