#!/usr/bin/env python3
import os
import shutil


src = '/home/calvin/projects/fluid/data/fs/7/imgs'
dest = '/home/calvin/datasets/real-male'
for folder in os.listdir(src):
    shutil.copyfile(
        os.path.join(src, folder, 'aligned.png'),
        os.path.join(dest, folder + '.png'),
    )
