info: 'modspace, beefier'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    # batch_size: 8
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.rec.RecTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.ae.e4e.E4e'
    facegen_exp: 'facegen/8/1'
    e_type: 'e4e'
    e_nc_base: 64

loss:
    type: 'ai_old.loss.rec.FancyRecLoss'
    perceptual_type: 'lpips'
