info: 'hre latent generator'
task: 'ai_old.task.tmp.TmpFacegenTask'
seed: 0
fp32: False
n_steps: 25000000
eval_freq: 100000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    # batch_size: 8
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.latent_gan.LatentGanTrainer'

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    init_from_exp: null
    G:
        type: 'ai_old.nn.models.facegen.latent.LatentGenerator'
        ae_exp: 'rec/21/3'
        z_dims: 512
        n_layers: 8
    D:
        type: 'ai_old.nn.models.discriminate.latent.LatentDiscriminator'
        z_dims: 512
        n_layers: 8

loss:
    type: 'ai_old.loss.latent_gan.LatentGanLoss'
    D:
        gp:
            freq: 16
            weight: 'auto'
