info: 'aae outer inpainter 192x192'
task: 'ai_old.task.outpaint.OutpaintTask'
seed: 0
fp32: false
n_steps: 25000000
eval_freq: 100000

dataset:
    type: 'ai_old.dataset.outpaint.Outpaint192Dataset'
    imsize: 192
    inner_imsize: 128
    batch_size: 32
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.outpaint.OutpaintAaeTrainer'
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.inpaint.outpaint.Outpainter'
    D:
        type: 'ai_old.nn.models.discriminate.outpaint.OutpaintDiscriminator'
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.aae.SimpleNonFaceAaeLoss'
    G:
        rec:
            weight: 10
            perceptual_type: 'lpips_alex'
    D:
        gp:
            freq: 16
            weight: 'auto'
