info: '128x128 stylegan2 without ppl reg'
task: 'ai_old.task.facegen.facegen.FacegenTask'

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    batch_size: 16

trainer:
    type: 'ai_old.trainer.gan.GanTrainerCustomSampler'
    n_epochs: 800
    model_ema: True

opt:
    type: 'adam'
    lr: 0.0002
    sch: 'flat_cosine'

model:
    type: 'ai_old.nn.models.facegen.style.StyleGeneratorWrapper'

loss:
    type: 'ai_old.loss.gan.GLoss'
    gan:
        type: 'hinge'

# discriminator
subtrainer:
    type: 'ai_old.trainer.discriminator.DiscriminatorTrainer'
    name: 'd'

    model:
        type: 'ai_old.nn.models.discriminate.style.StyleDiscriminator'

    loss:
        type: 'ai_old.loss.discrim.RegularizedDLoss'
        gan:
            type: 'hinge'
            weight: 1
        gp:
            freq: 4
            weight: 10

    opt:
        type: 'adam'
        lr: 0.0004
        sch: 'flat_cosine'
