info: '4x4 bottleneck, simple ae, trad perceptual'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: False
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.FfhqGanDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.rec.RecTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.ae.simple.SimpleAutoencoder'
    smallest_imsize: 4

loss:
    type: 'ai_old.loss.rec.FancyRecLoss'
    perceptual_type: 'trad'
