info: 'outer seg predictor from inner seg and inner img'
task: 'ai_old.task.outer_seg.OuterSegInpaintTask'
seed: 0
fp32: false
n_steps: 25000000
eval_freq: 40000

dataset:
    type: 'ai_old.dataset.outer_seg.OuterSeg192Dataset'
    imsize: 192
    inner_imsize: 128
    n_labels: 4
    # batch_size: 'auto'
    batch_size: 32
    batch_gpu: 'auto'
    xflip: false

trainer:
    type: 'ai_old.trainer.outer_seg.OuterSegTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.seg.outer_seg.OuterSegPredictor'
    pred_from_seg_only: false
    nc_base: 32

loss:
    type: 'ai_old.loss.outer_seg.OuterSegLoss'
