info: 'gan inversion, init g with facegen/8/1'
task: 'ai_old.task.tmp.TmpInversionTask'
seed: 0
fp32: False
n_steps: 25000000

dataset:
    type: 'ai_old.dataset.seed.GaussianSeedDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'

trainer:
    type: 'ai_old.trainer.inversion.GanInverter'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.encgen.inversion.GanInversionUnit'
    g_exp: 'facegen/8/1'
    e_type: 'slow_squeeze_excite'
    e_nc_base: 32
    e_n_layers_per_res: [2, 4, 8, 4, 2]
    e_norm: 'batch'
    e_weight_norm: false
    e_actv: 'mish'

loss:
    type: 'ai_old.loss.inversion.InversionLoss'
