name: 'zspace basic encoder'
trainer: 'ai_old.trainers.hqlr.HqlrTrainer'

deps:
    facegen:
        path: 'stylegan/stylegan2-ffhq-config-f.pt'
        frozen: True
        strict: False
    facerecog_loss:
        path: 'arcface/model_ir_se50.pth'
        frozen: True
        strict: False
        crop: True

dataset:
    type: 'hqlr'
    name: 'face-128'
    n: -1 # all
    n_samples: 32
    imsize: 128
    aug:
        flip: True

model:
    hqlr:
        type: 'ai_old.models.combined.zspace.Zspace'
        down: 'avgpool'
    e:
        type: 'ai_old.models.e.basic.BasicEncoder'
        nc_in: 3
        nc: 32
        k_first: 5
        n_down: 2
        n_res: 2
        dims_out: 512
        norm: 'pixel'
        weight_norm: True
        activation: 'prelu'
        padding: 'reflection'
    g:
        type: 'dep'
        dep: 'facegen'

train:
    loss:
        l2_pixel:
            weight: 1
        lpips:
            type: 'alex'
            weight: 1
        arcface_cosine:
            weight: 0.1
    train_generator: False
    epochs: 10
    batch_size: 8
    opt:
        type: 'ranger'
        lr: 0.001

eval:
    metrics: [
        'total_loss',
        'weighted_total_loss',
        'l2_pixel',
        'lpips',
        'arcface_cosine',
        'ssim',
    ]

inf:
    batch_size: 32
