info: 'non-adv binary brew 128x128, v1 e, resnet sg2 g, pixel only'
task: 'ai_old.task.distill.Sg2DistillTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.w_plus.BrewDataset'
    imsize: 128
    batch_size: 32
    batch_gpu: 'auto'
    xflip: false # implemented in trainer

trainer:
    type: 'ai_old.trainer.brew.BinaryBrewTrainer'
    xflip: false

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    teacher:
        type: 'ai_old.nn.models.facegen.brew.NonTriTeacher'
        lerp_exp: 'lerp/5/5'
        low_res_exp: 'distill/4/0'
    G:
        type: 'ai_old.nn.models.facegen.brew.Brew'
        nc_base: 32
        e_type: 'v1'
        e_pri_type: 'simple'
        e_mod_type: 'adalin'
        g_type: 'sg2'
        sg2_architecture: 'resnet'

loss:
    type: 'ai_old.loss.brew.NonAdvBrewLoss'
    G:
        rec:
            perceptual_type: null
            face_enabled: false
