info: '256x256 e4e no prog, lpips vgg'
task: 'ai_old.task.rec.RecTask'
seed: 0
fp32: false
n_steps: 25000000
eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.Ffhq256GanDataset'
    imsize: 256
    # batch_size: 'auto'
    batch_size: 8
    batch_gpu: 'auto'
    xflip: true

trainer:
    type: 'ai_old.trainer.aae.AaeTrainer'
    aug:
        enabled: true
        type: 'ada'
        target: 0.6
        speed: 'auto'
        freq: 4
        augpipe: 'bgc' # blit, geom, color

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    G:
        type: 'ai_old.nn.models.ae.e4e.E4e'
        no_prog: true
    D:
        type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        imsize: 256
        nc_base: 64
        nc_max: 512
        num_fp16_res: 4

loss:
    type: 'ai_old.loss.aae.SimpleAaeLoss'
    G:
        rec:
            weight: 10
            perceptual_type: 'lpips_vgg'
        delta_reg:
            weight: 0.0002
    D:
        gp:
            freq: 16
            weight: 'auto'
