info: 'e_ibg instance norm'
task: 'ai_old.task.blend.BlendRecTask'
seed: 0
fp32: False
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.realface.ffhq.BlendFfhqDataset'
    imsize: 128
    batch_size: 'auto'
    batch_gpu: 'auto'
    xflip: True

trainer:
    type: 'ai_old.trainer.rec.BlendRecTrainer'

opt:
    type: 'adam'
    hparams: 'auto-sg2'
    sch: 'flat'

model:
    type: 'ai_old.nn.models.encgen.blend.GeneratorInitializedBlendAutoencoder'
    g_exp: 'facegen/8/1'
    g_k_blend: 3
    e_ibg_norm: 'instance'

loss:
    type: 'ai_old.loss.rec.BlendFancyRecLoss'
