info: 'brew 128x128, 32 base, patch discrim'
task: 'ai_old.task.distill.Sg2DistillTask'
seed: 0
fp32: false
n_steps: 25000000
# eval_freq: 4000

dataset:
    type: 'ai_old.dataset.w_plus.BrewDataset'
    imsize: 128
    batch_size: 32
    batch_gpu: 'auto'
    xflip: false # implemented in trainer

trainer:
    type: 'ai_old.trainer.brew.AdvBrewTrainer'
    aug:
        enabled: false

opt:
    G:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'
    D:
        type: 'adam'
        hparams: 'auto-sg2'
        sch: 'flat'

model:
    teacher:
        type: 'ai_old.nn.models.facegen.brew.Teacher'
        lerp_exp: 'lerp/5/5'
    G:
        type: 'ai_old.nn.models.facegen.brew.Brew'
        nc_base: 32
    D:
        type: 'ai_old.nn.models.facegen.brew.Discriminator'
        # type: 'ai_old.nn.models.discriminate.fast_sg2.FastSg2Discriminator'
        # nc_base: 32
        # num_fp16_res: 4

loss:
    type: 'ai_old.loss.brew.BrewLoss'
    G:
        rec:
            weight: 10
            perceptual_type: 'lpips_alex'
    D:
        gp:
            freq: 16
            weight: 'auto'
